config/routes.rb
CoffeescriptcanvasCom::Application.routes.draw do
  
  namespace :tutorials do
    namespace :breakout do
      get 'index'
      get 'draw_a_circle'
      get 'add_some_color'
      get 'action'
    end
  end

  root :to => 'home#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/tutorials/breakout_controller.rb
class Tutorials::BreakoutController < ApplicationController
  layout 'tutorial'
  before_filter :load_defaults

  def index
  end

  def draw_a_circle
  end

  def add_some_color
  end

  private

    def load_defaults
      @title = "Make a Breakout clone with HTML5's <canvas> element"
      @steps_path = "/tutorials/breakout/steps"
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tutorials/breakout_helper.rb
module Tutorials::BreakoutHelper
end

app/views/home/index.html.erb
<div class="row">
  <div class="twelve columns">
    <h3 class="medium-weight">
      <%= link_to "Make a Breakout clone with HTML5's <canvas> element",
                  tutorials_breakout_index_path %></h3>
  </div>
</div>
<div class="row">
  <div class="eight columns">

    <p>
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
      quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
      consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
      cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
      proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
    </p>
    <p>
      Here is a re-creation of Bill Mill's <a href="http://billmill.org/static/canvastutorial/index.html" target="_blank">excellent canvas tutorial</a> with CoffeeScript
    </p>

  </div>
  <div class="four columns">
    <!-- <h5 class="light-weight">Recent Tutorials</h5> -->
    <div id="recent_tutorials" class="well">

      <div class="row">
        <div class="three columns">
          <img src="http://placehold.it/64x64">
        </div>
        <div class="eight columns">
          This is a callout with three columns on the left (for the avatar) and nine columns here for the text.
        </div>
      </div>

      <div class="row">
        <div class="three columns">
          <img src="http://placehold.it/64x64">
        </div>
        <div class="eight columns">
          This is a callout with three columns on the left (for the avatar) and nine columns here for the text.
        </div>
      </div>


      <div class="row">
        <div class="three columns">
          <img src="http://placehold.it/64x64">
        </div>
        <div class="eight columns">
          This is a callout with three columns on the left (for the avatar) and nine columns here for the text.
        </div>
      </div>

    </div>
  </div>
</div>

app/views/includes/_disqus.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">
    var disqus_shortname = 'coffeescriptcanvas';
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<a href="http://disqus.com" class="dsq-brlink">blog comments powered by <span class="logo-disqus">Disqus</span></a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&lt;canvas&gt;CoffeeScript&lt;/canvas&gt;</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <h1 class="medium-weight">
          <span style="color: #fff;">&lt;</span
          >canvas<span style="color: #fff;">&gt;</span
          ><span style="color: #CFC56A;">CoffeeScript</span
          ><span style="color: #fff;">&lt;/</span
          >canvas<span style="color: #fff;">&gt;</span
          ></h1>
      </div>
    </div>
  </div>
</header>

<div id="main_contents" class="container">
  <%= yield %>
</div>

<div class="container">
  <footer class="row">
    <section class="four columns">
      <h6><strong>Why CoffeeScript?</strong></h6>
      <p>foo</p>
    </section>
    
    <section class="four columns">
      <h6><strong>Why Canvas?</strong></h6>
      <p>foo</p>
    </section>
    
    <section class="four columns">
      <h6><strong>Who is this guy?</strong></h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p>
    </section>
  </footer>
</div>

</body>
</html>

app/views/layouts/tutorial.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>&lt;canvas&gt;CoffeeScript&lt;/canvas&gt;</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="container">
    <div class="row">
      <div class="twelve columns">
        <h1 class="medium-weight">
          <span style="color: #fff;">&lt;</span
          >canvas<span style="color: #fff;">&gt;</span
          ><span style="color: #CFC56A;">CoffeeScript</span
          ><span style="color: #fff;">&lt;/</span
          >canvas<span style="color: #fff;">&gt;</span
          ></h1>
      </div>
    </div>
  </div>
</header>

<div id="main_contents" class="container">
  <div class="row">
    <div class="twelve columns">
      <h3 class="medium-weight"><%= @title %></h3>
      <%= yield(:sub_header) %>
    </div>
  </div>
  <div class="row margin-top">
    <div class="nine columns">
      <%= yield %>
    </div>
    <div class="three columns">
      <div class="well">
        <%= render :partial => @steps_path %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <footer class="row">
    <section class="four columns">
      <h6><strong>Why CoffeeScript?</strong></h6>
      <p>foo</p>
    </section>
    
    <section class="four columns">
      <h6><strong>Why Canvas?</strong></h6>
      <p>foo</p>
    </section>
    
    <section class="four columns">
      <h6><strong>Who is this guy?</strong></h6>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt ut labore et dolore magna aliqua.</p>
    </section>
  </footer>
</div>

</body>
</html>

app/views/tutorials/breakout/_steps.html.erb
<ol>
  <li><%= link_to "Setup", tutorials_breakout_index_path %></li>
  <li><%= link_to "Create a Circle", tutorials_breakout_draw_a_circle_path %></li>
  <li><%= link_to "Add Some Color", tutorials_breakout_add_some_color_path %></li>
  <li><%= link_to "Action", tutorials_breakout_action_path %></li>
  <li>Library: an Interlude</li>
  <li>Bounce</li>
  <li>Add a Paddle</li>
  <li>The Keyboard</li>
  <li>The Mouse</li>
  <li>The Touch</li>
  <li>The Bricks</li>
  <li>Finished Touches</li>
  <li>Coda</li>
</ol>

app/views/tutorials/breakout/add_some_color.html.erb
<% content_for(:sub_header) do %>
  <p>Here is a re-creation of Bill Mill's 
    <a href="http://billmill.org/static/canvastutorial/index.html" target="_blank">excellent 
    canvas tutorial</a> with CoffeeScript</p>
<% end %>

<dl class="contained tabs">
  <dd><a href="#instructions" class="active">Instructions</a></dd>
  <dd><a href="#coffeescript">CoffeeScript</a></dd>
  <dd><a href="#javascript">JavaScript</a></dd>
  <dd><a href="#preview">Preview</a></dd>
  <dd><a href="#comments">Comments</a></dd>
</dl>

<ul class="tabs-content contained">
  <li class="active" id="instructionsTab">
    <h5 class="heavy-weight">Add Some Color</h5>
    <p>
      We've already made a <a href="/tutorials/breakout/draw_a_circle">ball</a>, now let's 
      make it move. In order to do so, we'll create a <code>draw()</code> function which 
      wipes the screen, draws the ball, then updates its current position. We'll use a call 
      to <code>setInterval(function, timeout)</code> in the <code>init()</code> function to 
      tell the browser to run our draw function every 10 milliseconds, creating the 
      illusion of movement.
    </p>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/be68949703caf708cd1c5d7df59758ef"></script></script>
    </p>
  </li>
  <li id="coffeescriptTab">
    <h5>breakout.js.coffee</h5>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/be68949703caf708cd1c5d7df59758ef"></script></script>
    </p>
  </li>
  <li id="javascriptTab">
    <h5>breakout.js</h5>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/00de93baf6989388904474075b819762"></script>
    </p>
  </li>
  <li id="previewTab">
    <a href="#" class="small button" onClick="reload('breakout_frame');" style="margin-bottom: 10px;">Reload</a>
    <br/>
    <iframe
      id="breakout_frame"
      style="border: 1px solid #ccc;"
      src="http://localhost:3000/examples/breakout/action/breakout.html" width="520" height="360"></iframe>
  </li>    
  <li id="commentsTab">
    <%= render :partial => "/includes/disqus" %>
  </li>
</ul>

app/views/tutorials/breakout/draw_a_circle.html.erb
<% content_for(:sub_header) do %>
  <p>Here is a re-creation of Bill Mill's 
    <a href="http://billmill.org/static/canvastutorial/index.html" target="_blank">excellent 
    canvas tutorial</a> with CoffeeScript</p>
<% end %>

<dl class="contained tabs">
  <dd><a href="#instructions" class="active">Instructions</a></dd>
  <dd><a href="#coffeescript">CoffeeScript</a></dd>
  <dd><a href="#javascript">JavaScript</a></dd>
  <dd><a href="#preview">Preview</a></dd>
  <dd><a href="#comments">Comments</a></dd>
</dl>

<ul class="tabs-content contained">
  <li class="active" id="instructionsTab">
    <h5 class="heavy-weight">Draw a Circle</h5>
    <p>
      We've already made a <a href="/tutorials/breakout/draw_a_circle">ball</a>, now let's 
      make it move. In order to do so, we'll create a <code>draw()</code> function which 
      wipes the screen, draws the ball, then updates its current position. We'll use a call 
      to <code>setInterval(function, timeout)</code> in the <code>init()</code> function to 
      tell the browser to run our draw function every 10 milliseconds, creating the 
      illusion of movement.
    </p>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/be68949703caf708cd1c5d7df59758ef"></script></script>
    </p>
  </li>
  <li id="coffeescriptTab">
    <h5>breakout.js.coffee</h5>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/be68949703caf708cd1c5d7df59758ef"></script></script>
    </p>
  </li>
  <li id="javascriptTab">
    <h5>breakout.js</h5>
    <p>
      <script type="text/javascript" src="http://snipt.net/embed/00de93baf6989388904474075b819762"></script>
    </p>
  </li>
  <li id="previewTab">
    <a href="#" class="small button" onClick="reload('breakout_frame');" style="margin-bottom: 10px;">Reload</a>
    <br/>
    <iframe
      id="breakout_frame"
      style="border: 1px solid #ccc;"
      src="http://localhost:3000/examples/breakout/action/breakout.html" width="520" height="360"></iframe>
  </li>    
  <li id="commentsTab">
    <%= render :partial => "/includes/disqus" %>
  </li>
</ul>

app/views/tutorials/breakout/index.html.erb
<% content_for(:sub_header) do %>
  <p>Here is a re-creation of Bill Mill's 
    <a href="http://billmill.org/static/canvastutorial/index.html" target="_blank">excellent 
    canvas tutorial</a> with CoffeeScript</p>
<% end %>

<dl class="contained tabs">
  <dd><a href="#setup" class="active">Setup</a></dd>
  <dd><a href="#comments">Comments</a></dd>
</dl>

<ul class="tabs-content contained">
  <li class="active" id="setupTab">
    <h4>Setup with a few files...</h4>
    <p>To start this project, we will create a new folder named <em>breakout</em> 
      and place into it three files:</p>
    <p><strong class="black">breakout.html</strong> will contain the HTML code for 
      our game. This will rarely be changed.</p>
    <p><strong class="black">breakout.js.coffee</strong> will contain the guts of 
      the game. This will be converted to raw JavaScript.</p>
    <p><strong class="black">breakout.js</strong> will contain our raw JavaScript 
      generated by <em>breakout.js.coffee</em>. This will never be modified directly.</p>
    <p>In the <em>breakout.html</em> file, let's paste the following code:</p>
    <p><script type="text/javascript" src="http://snipt.net/embed/60825c8af0e59997458d096129a36f93"></script></p>
  </li>
  <li id="commentsTab">
    <%= render :partial => "/includes/disqus" %>
  </li>
</ul>